### ISSUE TITLE
Add button does not become active even when the contract is approved.

### ISSUE THREAD

**Issue by colourfreak** [Computable-Finance/CoFiX-Web-User-Interface#10]
<img width="897" alt="Screenshot 2020-10-12 at 12 18 00" src="https://user-images.githubusercontent.com/51817359/95735631-5b7c7980-0c85-11eb-8f75-ac35aff4a6e0.png">

即使合同获得批准，“添加”按钮也不会激活。

**Comment by foxgem** [comment]
We redeployed a new version on https://www.cofix.io/white/index.html 7 hours ago. This issue should be fixed. Could u double check it? 

Thx.

**Comment by colourful-land** [comment]
The issue is still reproducible but occassionally. I sent you video privately.

**Comment by foxgem** [comment]
After checking again, it might a timing issue. We have a cache for state of approved, for this case, it might get old cached value. We will shorten the maxAge for it and test again.
