### ISSUE TITLE
When setting the "MAX' value for ETH, deduct the gas cost from the total balance 

### ISSUE THREAD

**Issue by James-Sangalli** [Computable-Finance/CoFiX-Web-User-Interface#20]
This prevents the error whereby the user selects max on the ether amount and get's an insufficient balance error

**Comment by foxgem** [comment]
Part of fix is included in 19b4215618fcf2dcf082759eb55470be66062a4f ,  in which UI will pass (max - gas cost) to service when max value is set for ETH. However future commit will include the logic of showing when ETH max value is set.

**Comment by foxgem** [comment]
Done, when max btn is clicked, (max - gas cost) will be the text of input. It is fixed by 8f15680d2fdd0da63ee69001dd8bfa7cd3c4b7ee

**Comment by colourful-land** [comment]
The problem persisted when I used today's code (on my PC served by ionic)

![imagen](https://user-images.githubusercontent.com/548435/95930833-4170a180-0e13-11eb-8470-cd3da2843fac.png)

**Comment by zhangzhongnan928** [comment]
> The problem persisted when I used today's code (on my PC served by ionic)
> 
> ![imagen](https://user-images.githubusercontent.com/548435/95930833-4170a180-0e13-11eb-8470-cd3da2843fac.png)

They used a "quick fix" which hardcoded to reduce the ETH by 0.02 ( 0.01 for oracle, 0.01 for gas)
Do you think it can work?

**Comment by colourful-land** [comment]
> They used a "quick fix" which hardcoded to reduce the ETH by 0.02 ( 0.01 for oracle, 0.01 for gas)
> Do you think it can work?

It depends on if you are swapping or providing liquidity.

In this example, the gas fee is 0.03108, so let's make the default liquidity providing gas fee higher than that, e.g. 0.05. I don't know what's the best gas amount for swap but 0.02 look like an alright number.

**Comment by foxgem** [comment]
Currently, for quick fix, we will use two constants for gas cost in swap and liquidity page:

- 0.02 for swap page
- 0.05 for liquidity page

If not ok, we can adjust these values later.

**Comment by zhangzhongnan928** [comment]
> Currently, for quick fix, we will use two constants for gas cost in swap and liquidity page:
> 
> * 0.02 for swap page
> * 0.05 for liquidity page
> 
> If not ok, we can adjust these values later.



> Currently, for quick fix, we will use two constants for gas cost in swap and liquidity page:
> 
> * 0.02 for swap page
> * 0.05 for liquidity page
> 
> If not ok, we can adjust these values later.

OK

**Comment by colourful-land** [comment]
The change is not effective. Observe in this screenshot, the "max" is simply balance - 0.1, not balance - 0.5 - 0.1. Using the latest code after  3a634a4 

![imagen](https://user-images.githubusercontent.com/548435/95963395-5ec56000-0e53-11eb-8e62-db236092c71f.png)

**Comment by James-Sangalli** [comment]
Since the gas limit can be known in advance, it might be pretty simple to just check the current gas price * the gas cost and then use that (possibly with a hardcoded offset in case the gas limit is set artificially high by the user agent)

**Comment by colourful-land** [comment]
> Since the gas limit can be known in advance, it might be pretty simple to just check the current gas price * the gas cost and then use that (possibly with a hardcoded offset in case the gas limit is set artificially high by the user agent)

Can you look into this and do a patch?

**Comment by foxgem** [comment]
here we have a quick & dirty fix:

```typescript
  @PCacheable({ maxAge: CACHE_FIVE_SECONDS })
  async currentGasFee() {
    const price = await this.http
      .get('https://ethgasstation.info/json/ethgasAPI.json')
      .toPromise<any>();

    return (700000 * (price.fastest / 10)) / 1000000000;
  }
```

this function return gasfee as eth unit, and 700000 is a hardcode gaslimit, which should meet all conditions.

Then, for this issue, we should do MAX_ETH_BALANCE - current gasfee - oracle fee.
